### ISSUE TITLE
hello,

### ISSUE THREAD

**Issue by Funny-dot** [1egoman/debundler#21]
![image](https://user-images.githubusercontent.com/27287970/68855370-11a7ae00-0719-11ea-812c-79cee1403ed2.png)
I have a question, can I help me?

**Comment by 1egoman** [comment]
I do not support this project anymore, sorry: https://github.com/1egoman/debundle#dragon-here-be-dragons-dragon

Here's the documentation if you haven't already read it over: https://github.com/1egoman/debundle/blob/master/DOCS.md
