### ISSUE TITLE
how debundle multi files such as mainifest.js vendor.js app.js 

### ISSUE THREAD

**Issue by lizhiqiang123321** [1egoman/debundler#24]
The package I build with webpack has multi files,not only one bundle.js.I tried node src/index.js a.js b.js c.js,but it did not work.Could you help me to resove this question?

**Comment by 1egoman** [comment]
I'm not maintaining this package in it's current state anymore, sorry: https://github.com/1egoman/debundle#dragon-here-be-dragons-dragon

(That being said, I don't believe this version of debundle ever supported this use case, though)
